### ISSUE TITLE
Abstaining on an MP lists the person as a reviewer

### ISSUE THREAD

**Issue by rcj4747** [philroche/lpshipit#9]
I filed an MP and in an emergency I performed a merge without reviews.  I made a comment to the effect and marked myself as abstaining.  (bzr managed source) I ran 'lpshipit.lpmessage --mp-owner foo'

"Merge lp:~foo into lp:~bar [a=rcj] [r=rcj]
...
"

**Comment by philroche** [comment]
Thank you. Now fixed:

`sudo snap refresh lpshipit`

**Comment by rcj4747** [comment]
Thanks Phil, rev 58 was installed and I confirmed the fix.  (btw, you might list the rev# of the snap when marking these fixed)
